---
title: Urban Simulation Report
author: 'Student number: 23083053'
bibliography: urban_simulation_report.bib
csl: harvard-cite-them-right.csl
execute:
  echo: false
format:
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    mainfont: Spectral
    sansfont: Roboto
    fontsize: 12pt
    papersize: a4
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: true
    colorlinks: true
    highlight-style: github
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.15.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

## Part 1: London's Underground Resilience

### Topological Network

### Flows: Weighted Network


## Part 2: Spatial Interaction Models

In the second part, we will analyse the OD matrix of the London Underground.

### Models and Calibration

#### Family of Spatial Interaction Models

The family of spatial interaction models are as follows:

The **unconstrained model** only constrains the model with matching the total flows with the observed value, written as

$$
T_{ij} = K O^{\alpha}_i D^{\gamma}_j f(c_{ij})
$$

where $K$ is the constant

$$
K = \frac{T}{\sum_i \sum_j O^{\alpha}_i D^{\gamma}_j f(c_{ij})}
$$

so that the total number of journeys are constrained.

The **singly constrained model** constrains the total number of observations for each component at the origin or the destination. The origin constrained model fixes the total number of journeys at the origin, as:

$$
T_{ij} = A_i O^{\alpha}_i D^{\gamma}_j f(c_{ij})
$$

The destination constrained model fixes the total number at the destination. The parameter $A_i$ is determined so that the total at the origin is constrained, that is:

$$
\sum_j T_{ij} = O_i \therefore A_i = \frac{1}{\sum_j D_j f(c_{ij})}
$$

Similarly, the **destination constrained model** constrains the total at the destination.

$$
\begin{gather}
T_{ij} = O^{\alpha}_i B_j D^{\gamma}_j f(c_{ij}) \\
\text{where} \left (B_j = \frac{1}{\sum_i O_i f(c_{ij})} \right)
\end{gather}
$$

The **doubly constrained model** constrains both the total at the origin and destination.

$$
T_{ij} = A_i O^{\alpha}_i B_j D^{\gamma}_j \exp(-\beta c_{ij})
$$

#### Calibration

The dataset used for analysis have the following data for every origin-destination pair for the London Underground Stations.

- population of origin
- jobs at the destination
- distance between origin and destination
- flow from the origin to the destination

Using this dataset, we will use the doubly constrained model to estimate the best cost function and parameters by comparing with the observed flow. Constraining both the total journeys for both the origin and destination will enable the full utilisation of observed data, enabling a most accurate calibration of the cost function.

The doubly constrained model after a logarithm transformation into a Poisson expression can be written as:

$$
\begin{gather}
\ln(T_{ij}) = \ln A_i + \ln O^{\alpha}_i + \ln B_j + \ln D^{\gamma}_j + \ln f(c_{ij}) \\
\end{gather}
$$

We will compare the negative exponential and inverse power relationships as the cost function $f(d_{ij})$ as follows:

$$
f(d_{ij}) = 
\begin{cases}
\exp(-\beta c_{ij}) \text{ (Negative Exponential)} \\
c^{-\beta}_{ij}  \text{ (Inverse Power)} 
\end{cases}
$$

For each cost function, we have run the Poisson Regression to calculate the optimal parameter $\beta$. 

| Cost Function | Parameter $\beta$ | $R^2$ value |
| --- | --- | --- |
| Negative exponential $f(c_{ij}) = \exp(-\beta c_{ij})$ | $\beta = 1.543 \times 10^{-4}$ | $R^2 = 0.4979$ |
| Inverse Power $f(c_{ij}) = c^{-\beta}_{ij}$ | $\beta = 9.096 \times 10^{-1}$ | $R^2 = 0.4077$ |

: Comparison of results for the doubly constrained model using inverse power and negative exponential cost functions.

From these results, the negative exponential model for the cost function has a better fit to the observed flows. When considering the scenarios, the cost function
$$
f(c_{ij}) = \exp(-1.543 c_{ij})
$$

will be used.

### Scenarios

The scenarios we will observe in this report are as follows:

| Scenario | Explanation |
| :--- | :--- |
| Scenario A | Jobs at Canary Wharf decrease by 50 % |
| Scenario B | Increase in cost of transport - considering 2 parameters |

: The scenarios explored in this report.

#### Scenario A

We will first decrease the number of jobs at Canary Wharf by 50%, from the original 58,772 to 29,386. We will use the origin-constrained model to simulate this behaviour. The procedure is as follows:

1. Calculate the flow based on the origin-constrained model $T_{ij} = A_i O_i D^{\gamma}_j \exp(-\beta c_{ij})$ to retrieve the optimal $\gamma$ value for this dataset. Values for parameter $\beta$ is determined upon calibration.
2. Reduce the number of jobs at Canary Wharf (transform $D_j$ into $D'_j$)
3. Recalibrate the adjusted $A'_i$ parameter with the new distribution of using the relationship $A'_i = \frac{1}{\sum_j D'^{\gamma}_j f(c_{ij})}$
4. Calculate the new flows using the relationship $T'_{ij} = A'_i O_i D'^{\gamma}_j \exp(-\beta c_{ij})$

#### Scenario B

We will consider 2 scenarios for 


#### Discussion




---

Word count: x words
GitHub repository (as hyperlink): [Urban_Simulation_Report](https://github.com/sokimura39/Urban_Simulation_Report)

{{< pagebreak >}}

## References


